apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-nginx
  namespace: default
  labels:
    app: nginx-ds
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: my-nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
